### ISSUE TITLE
Create new TP with SpaCy

### ISSUE THREAD

**Issue by madewild** [madewild/ingling#1]
In a Jupyter notebook

**Comment by madewild** [comment]
Investigate https://spacy.io/api/matcher

**Comment by madewild** [comment]
@devironl check this matcher explorer: https://demos.explosion.ai/matcher

**Comment by madewild** [comment]
Detailed doc: https://spacy.io/usage/rule-based-matching

**Comment by devironl** [comment]
The explorer is nice but does not include French models. It would be great if we can find the code, fork it and include them

**Comment by devironl** [comment]
Hello Max
I am done with Python and Spacy. Can you have a look ?
To share with the students I think that giving them the notebook files directly will be easier (we ensure that they are not losing their work by working on "our" version without being able to save it.
What do you think ?

**Comment by madewild** [comment]
So you mean not using colab at all?

**Comment by devironl** [comment]
Sorry not clear. I meant using colab and importing the files directly from there (and saving in their own drives)

**Comment by madewild** [comment]
If they use https://colab.research.google.com/github/madewild/ingling/blob/main/Python/tp_spacy.ipynb#scrollTo=fb37vcYxhWFC there is a "Copy to Drive" button, that's the easiest, no? Rather than sharing local files on Moodle.

I went through the spaCy notebook and it looks good.

**Comment by madewild** [comment]
We should also briefly explain:
- what is Jupyter, what is a notebook
- what is Colab, and difference between a local Python installation vs cloud-based one
- what is pip, how we import libraries, and the ! notation for executing bash commands
Let's make this slowly not to confuse the students too much.

**Comment by devironl** [comment]
Indeed ! Normally they are familiar with Colab already because they had to use it for the previous exercise
But let's do a reminder!!

**Comment by devironl** [comment]
Hey Max. I had a look on the exercise, looks nice :-)
Only one small thing: at the end you are talking about the readability of the code but they only need to give back a json file.
For the rest, it looks great

**Comment by madewild** [comment]
Fixed
