### ISSUE TITLE
Review new TP

### ISSUE THREAD

**Issue by madewild** [madewild/ingling#11]
Finally I let the matcher for everyone as a base task (but without the new to provide the JSON code) + asked to test 2 other tasks seen during the session (cf. #10 ).

Can you have a look at https://github.com/madewild/ingling/blob/main/Python/tp_spacy.ipynb and give me feedback?

We can mention orally (and demonstrate) how ChatGPT etc. can be leveraged to help with the coding part, since the goal is more to understand what is going on rather than coding these things from scratch.

**Comment by devironl** [comment]
It looks great and it encourages creativity. I will adapt the exercises given during the course so that we cover more topics there as well
